### ISSUE TITLE
email.it non va da qualche settimana

### ISSUE THREAD

**Issue by marcobartman** [matteobaccan/html2pop3#183]
### Discussed in https://github.com/matteobaccan/html2pop3/discussions/182

<div type='discussions-op-text'>

<sup>Originally posted by **marcobartman** November 17, 2021</sup>
Ciao! Purtroppo gli account email.it hanno smesso di funzionare da qualche settimana, e restituiscono "invalid password" anche se ovviamente le credenziali sono corrette. User inviata correttamente come "<utente>@email.it", e crittografia non abilitata, come richiesto. Problema riscontrato con tutte le caselle email.it (ne ho più di una, su PC diversi). Riesci ad aggiornare? Sarebbe top! Grazie mille come sempre! ;-)</div>

**Comment by matteobaccan** [comment]
ciao

i test su master passano senza problemi email.it, non vorrei sia un problema della 3.0.6
Hai possibilità di provare con i source su master? 

ciao
matteo

**Comment by marcobartman** [comment]
Purtroppo mi cogli impreparato, nel senso che non ho idea di cosa mi stai chiedendo... mi spiace! Se non troppo complesso puoi magari indicarmi i passi per testare questa cosa, non so...

**Comment by forlanim** [comment]
Buongiorno, dopo aver visto questa richiesta avevo provato  a compilare con eclipse (in ambiente windows) scaricando i sorgenti, ma ho ottenuto solo errori su dipendenze.
Purtroppo non ero sul mio PC e nemmeno avevo tempo per controllare come si deve e devo dire che java proprio non fa parte delle mie conoscenze.
Ora che dovrei avere un poco di tempo in più vorrei fare un nuovo tentativo, ma non riesco a trovare indicazioni sull'ambiente necessario e/o versioni specifiche.
Grazie

**Comment by matteobaccan** [comment]
Ciao

ho rilasciato la 3.0.7 che risolve il problema: email.it era cambiato di nuovo.
HTML2POP3, fino alle 3.0.7, funzionava con java 8.
Ora il master è stato portato a java 11. Mantengo la versione bassa in modo da allargare l'installazione

ciao
matteo
